up:
	./scripts/deploy.sh dev

migrate:
	./scripts/migrate.sh dev

list:
	./scripts/ps.sh dev

test:
	./scripts/test.sh dev

clean:
	./scripts/clean.sh

reset:
	$(MAKE) clean
	$(MAKE) up

minikube:
	./scripts/minikube_start.sh
