language: python
python:
  - 3.6
cache: pip
install: pip install -r requirements.txt
before_script:
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis CI"
script: make test
sudo: false
